#!/usr/bin/env python

from abc import ABCMeta
from collections.abc import Sequence
from typing import overload, Literal
from .spiralpolar import SpiralPolarBase
from ._typal import Vecf, Array2f

class SpiralArchimedesBase(SpiralPolarBase, metaclass=ABCMeta):
    def __init__(self, b: float, n: float, r0: float): ...

    @overload
    def theta_to_r(self, theta: float) -> float: ...
    @overload
    def theta_to_r(self, theta: Sequence[float] | Vecf) -> Vecf: ...

    @overload
    def r_to_theta(self, r: float) -> float: ...
    @overload
    def r_to_theta(self, r: Sequence[float] | Vecf) -> Vecf: ...

    @overload
    def arclength_to_theta(self, 
                           s: float,
                           s0: float = 0.0,
                           t0: float | None = None
                           ) -> float: ...
    @overload
    def arclength_to_theta(self, 
                           s: Sequence[float] | Vecf,
                           s0: float = 0.0,
                           t0: float | None = None
                           ) -> Vecf: ...

    def get_tangent(self,
                    v: float | Sequence[float] | Vecf,
                    var: Literal['r', 'theta', 's'] = 's'
                    ) -> Vecf | Array2f: ...


class SpiralArchimedesGeneral(SpiralArchimedesBase):
    def __init__(self, b: float, n: float, r0: float): ...

    @overload
    def _func_arclength(self, theta: float) -> float: ...
    @overload
    def _func_arclength(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_arclength_der(self, theta: float) -> float: ...
    @overload
    def _func_arclength_der(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_curvature(self, theta: float) -> float: ...
    @overload
    def _func_curvature(self, theta: Vecf) -> Vecf: ...


class SpiralArchimedes(SpiralArchimedesBase):
    def __init__(self, b: float, r0: float): ...

    @overload
    def _func_arclength(self, theta: float) -> float: ...
    @overload
    def _func_arclength(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_arclength_der(self, theta: float) -> float: ...
    @overload
    def _func_arclength_der(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_curvature(self, theta: float) -> float: ...
    @overload
    def _func_curvature(self, theta: Vecf) -> Vecf: ...


class SpiralFermat(SpiralArchimedesBase):
    def __init__(self, b: float, r0: float): ...

    @overload
    def _func_arclength(self, theta: float) -> float: ...
    @overload
    def _func_arclength(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_arclength_der(self, theta: float) -> float: ...
    @overload
    def _func_arclength_der(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_curvature(self, theta: float) -> float: ...
    @overload
    def _func_curvature(self, theta: Vecf) -> Vecf: ...


class SpiralHyperbolic(SpiralArchimedesBase):
    def __init__(self, b: float, r0: float): ...

    @overload
    def _func_arclength(self, theta: float) -> float: ...
    @overload
    def _func_arclength(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_arclength_der(self, theta: float) -> float: ...
    @overload
    def _func_arclength_der(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_curvature(self, theta: float) -> float: ...
    @overload
    def _func_curvature(self, theta: Vecf) -> Vecf: ...


class SpiralLituus(SpiralArchimedesBase):
    def __init__(self, b: float, r0: float): ...

    @overload
    def _func_arclength(self, theta: float) -> float: ...
    @overload
    def _func_arclength(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_arclength_der(self, theta: float) -> float: ...
    @overload
    def _func_arclength_der(self, theta: Vecf) -> Vecf: ...

    @overload
    def _func_curvature(self, theta: float) -> float: ...
    @overload
    def _func_curvature(self, theta: Vecf) -> Vecf: ...
